
CREATE DATABASE CustomerShardUS;
GO
CREATE DATABASE CustomerShardEU;
GO
CREATE DATABASE CustomerShardZH;
GO
CREATE DATABASE CustomerShardBR;
GO
CREATE LOGIN webReader WITH PASSWORD = N'Pwd123456';
GO
CREATE LOGIN webWriter WITH PASSWORD = N'Pwd567890';
GO
